services:
  dotnet-api:
    isolation: ${ISOLATION}
    build:
      context: .
    environment:
      OTLPEXPORTER__ENDPOINT: http://otel-collector:4317
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8080/healthz"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dotnet-api.loadbalancer.server.port=8080"
      - "traefik.http.routers.dotnet-api.entrypoints=websecure"
      - "traefik.http.routers.dotnet-api.rule=Host(`${DOTNET_API_HOST}`)"
      - "traefik.http.routers.dotnet-api.tls=true"