services:
  otel-collector:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-otelcol-contrib:${VERSION:-latest}
    isolation: ${ISOLATION}
    build:
      context: ./docker/build/otel-collector
    ports:
      - 4317:4317 # OTLP gRPC receiver
    environment:
      SQL_SERVER: ${SQL_SERVER}
      SQL_SA_LOGIN: ${SQL_SA_LOGIN}
      SQL_SA_PASSWORD: ${SQL_SA_PASSWORD}
