services:
  otel-collector:
    isolation: ${ISOLATION}
    build:
      context: ./docker/build/otel-collector
      args:
        BASE_IMAGE: otel/opentelemetry-collector-contrib:latest-windows-2022-amd64
    ports:
      - 4317:4317 # OTLP gRPC receiver
    environment:
      SQL_SERVER: ${SQL_SERVER}
      SQL_SA_LOGIN: ${SQL_SA_LOGIN}
      SQL_SA_PASSWORD: ${SQL_SA_PASSWORD}
      NEW_RELIC_API_KEY: ${NEW_RELIC_API_KEY}
      GRAFANACLOUD_ENDPOINT: ${GRAFANACLOUD_ENDPOINT}
      GRAFANACLOUD_USERNAME: ${GRAFANACLOUD_USERNAME}
      GRAFANACLOUD_PASSWORD: ${GRAFANACLOUD_PASSWORD}
      SIGNOZ_ENDPOINT: ${SIGNOZ_ENDPOINT}
