services:
  dotnet-listener:
    isolation: ${ISOLATION}
    build:
      context: .
    environment:
      OTLPEXPORTER__ENDPOINT: http://otel-collector:4317
      SERVICEBUS__CONNECTIONSTRING: ${AZURE_SERVICEBUS_CONNECTIONSTRING}
